name: tcbike
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_screenutil: ^5.6.0
  get: ^4.6.5
  
  flutter_svg: ^1.1.6
  flutter_slidable: ^2.0.0
  shimmer: ^2.0.0

  http: ^0.13.5
  image_picker: ^0.8.5+3
  internet_connection_checker: ^1.0.0+1
  google_sign_in: ^5.4.2
  flutter_widget_from_html: ^0.9.0+2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0


  sqflite: ^2.2.2
  path: ^1.8.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800

